### ISSUE TITLE
Pair with Scott

### ISSUE THREAD

**Issue by ajrobbins** [azavea/pwd-waterworks-revealed#180]
Pair with Scott to review the device orientation implementation in the new prototype.

**Comment by kellyi** [comment]
- [x] cursory familiarization with how geolocation works in original app (check how PhoneGap uses native APIs)
- [x] review new prototype branch, discuss with @lederer 
- [x] cursory research into viability of the phone orientation element of the prototype (compass-bearings) (targets are Android and iOS)

Deliverable is a short write-up ADR on rec's for implementing geolocation & the viability of orientation feature.

**Comment by kellyi** [comment]
In ADR: include some potential ideas about how to solve issues with location/orientation accuracy -- without necessarily deciding on one or another.

**Comment by kellyi** [comment]
Got both the original and new prototype running and checked out the geolocation API. Seems like it works very roughly indoors. The device orientation API seems to work really well in the new prototype.

This was on iOS, btw, so I don't know whether this also goes for Android.

**Comment by kellyi** [comment]
Seems like this https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API might be viable for detecting whether the app's been foregrounded or backgrounded -- will test it out a tiny bit to see.

**Comment by kellyi** [comment]
Checked out the device orientation browser API a bit and it seems like that'll be easier to use than the geolocation API. Mentioned above that the new prototype is working great; I tried out a small app to log out the alpha/beta/gamma values of the geolocation API and they seemed to be very accurate.

As is done in the new prototype, I think we're going to have to debounce requests to get these values since the orientation API seems to slough off data pretty rapidly.

Will write up a three paragraph assessment in the morning. I don't have ready access to an Android phone so all my testing was done on iOS so far.

**Comment by kellyi** [comment]
The demo under the Example section of this page -- https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API -- has a video that, if playing, gets paused when the browser window it's in is not visible then restarts when its browser window's visible again.

It seems like it may work for resuming geolocation if the user were to put the phone into standby mode and then later re-open the window with the app in it.
